### PR TITLE
Initial copy-text files

### PR DESCRIPTION
**Pull request by batzlerg**
Copy-text functionality ported from bunsen, maintaining commit history

### CODE REVIEW

**Comment by antialias** [comment]
go ahead and merge this when you're happy with it

**Comment by antialias** [comment]
actually, can you do a force-push to master instead of merging this PR? It would be cleaner that way

**Comment by antialias** [comment]
hold off, I want to try something...

**Comment by batzlerg** [comment]
standing by

**Comment by antialias** [comment]
cleaned up history a bit and force-pushed directly to master. closing this PR

**Pull request closed without merging**
